### ISSUE TITLE
Maximizes window after shifting focus

### ISSUE THREAD

**Issue by pojomojo1982** [xurei/hyperkeys#7] opened 2020-09-07 23:21 UTC
If window is maximized, it un-maximizes window after shifting focus. Almost makes it unusable as I thought the purpose was to enable hotkeys for fast switching and save time with ALT+TAB.

I would really appreciate it if you're able to fix this issue - it should be possible to introspect the state of the window and then conditionally invoke the necessary APIs to only shift focus.

**Comment by xurei** [comment] 2020-09-08 08:44
Hi @pojomojo1982, thanks for you interest in Hyperkeys!

Could you provide:
- the OS your working with (I guess Windows?)
- the version you're currently using

Version 1.1.7 has solved a bug that might be related to your issue.

**Comment by pojomojo1982** [comment] 2020-09-08 22:14
Hi @xurei 

I'm using Windows 10 Home version 2004. I'm using Hyperkeys version 1.1.8.

I checked again just to be sure - after setting up the Window PIN (or Window PIN by name) - when the macro is executed on a maximized window (or a windows that is glued to an edge (for e.g. using Windows Key + Right arrow key), the window no longer remains in its original state after activating the macro. Focus does shift to the window correctly though.

Thanks!

**Comment by pojomojo1982** [comment] 2020-09-09 02:18
Just some additional info - I believe above only happens in a multi-monitor setup.

**Comment by xurei** [comment] 2020-09-09 09:15
Yes, I'm aware of this issue.
It happens only on Windows due to a limitation of it's API, but I thought it was fixed in the latest version.

The multi-monitor setup might be a lead...

If possible, could you make a screencast so I can see exactly what is going on and reproduce the bug?

**Comment by pojomojo1982** [comment] 2020-09-09 23:11
@xurei Here's a screen cast. I can now confirm that it has nothing to do with multiple monitors. This screen cast was made when no other monitors were connected. 

[https://1drv.ms/u/s!AqjkaRBXok-401LR30ySANU0AwLT?e=Q6dSvM](link to screencast)

**Comment by xurei** [comment] 2020-09-10 08:33
Thanks for the screencast. I'm going to investigate this during the weekend.

I'm not seeing the keystrokes on the video, hence can you confirm that you tried both "Window Pin" and "Window Pin by Name", and that both have the issue?

Thanks again for your help.

**Comment by pojomojo1982** [comment] 2020-09-11 23:53
Happy to help - yes, the issue exists with both “Window Pin” and “Window PIN by name”. 

Hopefully you’re able to figure it out.

**Comment by xurei** [comment] 2020-09-12 13:03
I did some investigation and so far :

- I was able to reproduce the bug with "Window Pin By Name". I think I know what's going on...

- For "Window Pin", I can reproduce the bug only once. The first switch is restoring the window only the first time. After that, any switch to the window is going well.
Do you have this behavior as well ?

**Comment by xurei** [comment] 2020-09-13 20:02
I have made a new version that should be fixing the issue, or at least make it happen only once.
Can you try this [pre-release](https://github.com/xurei/hyperkeys/releases/tag/v1.1.9-rc1) and tell me if it works?

**Comment by greggannicott** [comment] 2020-12-15 11:26
For what it's worth, I've been experiencing this issue (specifically with Window Pin By Name), and the pre-release version you linked to has fixed it for me.

Thanks.

**Comment by xurei** [comment] 2020-12-16 16:48
As this seems to be fixed in 1.1.9 release, I'm closing this issue. 

If the problem persists, please comment below to reopen it.

**Closed by xurei** 2020-12-16 16:48 UTC
